MooncakePortal/urls.py
"""
Definition of urls for MooncakePortal.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'app.views.home', name='home'),
    url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^accounts/profile/', 'app.views.profile', name='profile'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^customizationtool/$', 'customizationTool.views.mainpage', name='customizationToolmainpage'),
    url(r'^documentation/', 'customizationTool.views.documentation', name='documentationRedirect'),
    url(r'^home/features/', 'customizationTool.views.documentation', name='homeFeatureRedirect'),
    url(r'^reports/$', 'reports.views.mainpage', name='reportsmainpage'),
    url(r'^QA/$', 'QA.views.mainpage', name='QAmainpage'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ut/', include('UT.urls')),
    url(r'^landingpage/', include('landingPage.urls')),
    url(r'^sotracker/', include('SOTracker.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

UT/urls.py
from django.conf.urls import url

from . import views

app_name = 'UT'
urlpatterns = [
    url(r'^$', views.mainpage, name='UTmainpage'),
    url(r'^reportForAll/$', views.reportForAll, name='reportForAll'),
    url(r'^getlogs/(?P<user_id>[0-9]+)/(?P<record_num>[0-9]+)/$', views.getLog, name='getlogs'),
    url(r'^getlogs/(?P<user_id>[0-9]+)/from(?P<start>[0-9|\-]+)to(?P<end>[0-9|\-]+)/(?P<page>[0-9]+)/$', views.getLogByDuration, name='getLogByDuration'),
    url(r'^updatearticles/(?P<service_id>[0-9]+)/$', views.updatearticles, name='UTupdatearticles'),
    url(r'^submitreport$', views.submitReport, name='submitReport'),
    url(r'^recordsearch/(?P<labor_id>[0-9]+)/from(?P<start_date>[0-9|\-]+)to(?P<end_date>[0-9|\-]+)/(?P<labor_type>\w+)/$', views.recordSearch, name='recordSearch'),
    url(r'^addarticles/$', views.addArticles, name='addArticles'),
    url(r'^selectarticleswithtext/$', views.selectArticlesWithText, name='selectArticlesWithText'),
]

UT/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Labor_type(models.Model):
    type_name = models.CharField(max_length=50)
    deliverability = models.BooleanField()

    def __str__(self):
        return self.type_name

class Record(models.Model):
    comments = models.TextField()
    creater = models.ForeignKey(User)
    submit_time = models.DateTimeField()
    duration = models.IntegerField()
    labor_type = models.ForeignKey(Labor_type)
    UT_time = models.DateTimeField(default="2015-12-01")

    def __str__(self):
        return self.creater.username+", "+str(self.submit_time)+", "+str(self.labor_type)

class Service(models.Model):
    name = models.CharField(max_length=50)
    relative_path = models.CharField(max_length=100, default="articles/")
    def __str__(self):
        return self.name

class Article(models.Model):
    service = models.ForeignKey(Service)
    status = models.CharField(max_length=50)
    filename = models.CharField(max_length=255)
    def __str__(self):
        return self.filename

class Record_article(models.Model):
    record = models.ForeignKey(Record)
    article = models.ForeignKey(Article)

    class Meta:
        unique_together = (("record", "article"),)

class Work_date_exception(models.Model):
    date = models.DateTimeField()
    holiday = models.BooleanField()

    class Meta:
        unique_together = (("date"),)

UT/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseBadRequest
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timezone, timedelta
from .models import Service, Article, Labor_type, Record, Record_article, Work_date_exception
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.db.models import Sum
from django.views.decorators.cache import never_cache
from math import floor, ceil
from MooncakePortal.clearCache import expire_cache
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required
def mainpage(request):
    user_id = request.user.id
    if Group.objects.get(name="Administrator") in request.user.groups.all():
        disabled = False
    else:
        disabled = True
    users = Group.objects.get(name="User").user_set.all()
    services = Service.objects.order_by("id")
    articles = Article.objects.filter(service_id = services[0].id).order_by("filename")
    labor_types = Labor_type.objects.order_by("id")
    today = datetime.now(timezone(timedelta(0, 28800)))
    start_day = today - timedelta(0, 86400*(today.day-1))
    return render(
        request,
        'UT/mainpage.html',
        context_instance = RequestContext(request,
        {
            'title':'UT',
            'year':datetime.now().year,
            "services":services,
            "articles":articles,
            "labor_types":labor_types,
            "users":users,
            "today":datetime.strftime(today, "%Y-%m-%d"),
            "start_day":datetime.strftime(start_day, "%Y-%m-%d"),
            "user_id":user_id,
            "disabled":disabled,
        })
    )

@login_required
def reportForAll(request):
    user_id = request.user.id
    if Group.objects.get(name="Administrator") in request.user.groups.all():
        disabled = False
    else:
        disabled = True
    users = Group.objects.get(name="User").user_set.all()
    services = Service.objects.order_by("id")
    articles = Article.objects.filter(service_id = services[0].id).order_by("filename")
    labor_types = Labor_type.objects.order_by("id")
    today = datetime.now(timezone(timedelta(0, 28800)))
    start_day = today - timedelta(0, 86400*(today.day-1))
    return render(
        request,
        'UT/reportForAll.html',
        context_instance = RequestContext(request,
        {
            'title':'UT',
            'year':datetime.now().year,
            "services":services,
            "articles":articles,
            "labor_types":labor_types,
            "users":users,
            "today":datetime.strftime(today, "%Y-%m-%d"),
            "start_day":datetime.strftime(start_day, "%Y-%m-%d"),
            "user_id":user_id,
            "disabled":disabled,
        })
    )

@login_required
def updatearticles(request, service_id):
    articles = Article.objects.filter(service_id = int(service_id)).order_by("filename")
    return render(
        request,
        'UT/articleList.html',
        context_instance = RequestContext(request,
        {
            "articles":articles,
        })
    )

@login_required
def submitReport(request):
    print(request.POST["submitDate"])
    record = Record(comments=request.POST["comments"], creater=request.user, submit_time=datetime.now(timezone(timedelta(0, 28800))), UT_time=datetime.strptime(request.POST["submitDate"] + " +0800", "%Y-%m-%d %z"), duration=int(request.POST["duration"]), labor_type_id=int(request.POST["labor_type"]))
    record.save()
    article_ids = [int(id) for id in request.POST["article_ids"].split(",") if id!=""]
    for id in article_ids:
        record_article = Record_article(record=record, article_id=id)
        print("article: "+str(id))
        record_article.save()
    return redirect("/ut/")

@never_cache
@login_required
def recordSearch(request, labor_id, start_date, end_date, labor_type):
    currentUser = request.user
    user = User.objects.get(id=int(labor_id))
    if not(Group.objects.get(name="Administrator") in currentUser.groups.all() or user.id == currentUser.id):
        return HttpResponse("Sorry, you don't have permission to view %s's report"%user.username)
    start = datetime.strptime(start_date + " +0800", "%Y-%m-%d %z")
    end = datetime.strptime(end_date + " +0800", "%Y-%m-%d %z")
    delta = end - start
    days = delta.days
    holiday = 0
    startWeekday = start.weekday()
    endWeekday = end.weekday()
    if startWeekday==5:
        holiday+=2
        days-=2
        startWeekday=0
    elif startWeekday==6:
        holiday+=1
        days-=1
        startWeekday=0
    if endWeekday==5:
        holiday+=1
        days-=1
        endWeekday=4
    elif endWeekday==6:
        holiday+=2
        days-=2
        endWeekday=4
    weeks = floor(days/7.0)
    if startWeekday>endWeekday:
        weeks+=1
    holiday+= weeks*2
    print(holiday)
    end = end + timedelta(0, 86399)
    exceptions = Work_date_exception.objects.filter(date__gte=start, date__lte=end)
    for exception in exceptions:
        if exception.holiday:
            holiday+= 1
        else:
            holiday-= 1
    workdays = delta.days+1-holiday
    query = user.record_set.filter(UT_time__gte=start,
                                   UT_time__lte=end)
    if labor_type != "all":
        query = query.filter(labor_type=int(labor_type))
    
    query2 = query.filter(labor_type=7)
    totalminutes = query.aggregate(Sum("duration"))['duration__sum']
    stackoverflowminutes = query2.aggregate(Sum("duration"))['duration__sum']
    if stackoverflowminutes==None:
        stackoverflowminutes = 0
    if totalminutes==None:
        totalminutes = 0
    totalhours = totalminutes/60.0
    contenthours = (totalminutes - stackoverflowminutes)/60.0
    username = user.username
    if workdays<=0:
        percentage = "N/A"
        contentpercentage = "N/A"
    else:
        percentage = "{:10.2f}".format(totalhours*100/(workdays*8.0))
        contentpercentage = "{:10.2f}".format(contenthours*100/(workdays*8.0))
    return render(
        request,
        'UT/reportTable.html',
        context_instance = RequestContext(request,
        {
            "totalminutes":totalminutes,
            "totalhours":"{:10.2f}".format(totalhours),
            "username":username,
            "workdays":workdays,
            "percentage":percentage,
            "contenthours":"{:10.2f}".format(contenthours),
            "contentpercentage":contentpercentage,
        })
    )

@login_required
def getLog(request, user_id, record_num):
    currentUser = request.user
    user = User.objects.get(id=int(user_id))
    if not(Group.objects.get(name="Administrator") in currentUser.groups.all() or user.id == currentUser.id):
        return HttpResponse("Sorry, you don't have permission to view %s's records"%user.username)
    records = Record.objects.filter(creater=user).order_by("-id")[:int(record_num)]
    for record in records:
        record.UT_time = datetime.strftime(record.UT_time.astimezone(timezone(timedelta(0, 28800))), "%b. %d, %Y")
    if Group.objects.get(name="Administrator") in currentUser.groups.all():
        isAdmin = True
        users = Group.objects.get(name="User").user_set.all()
    else:
        isAdmin = False
        users = []
    return render(
        request,
        'UT/records.html',
        context_instance = RequestContext(request,
        {
            "records":records,
            "isAdmin":isAdmin,
            "users":users,
            "start":0,
            "end":10,
        })
    )

@login_required
@never_cache
def getLogByDuration(request, user_id, start, end, page):
    currentUser = request.user
    user = User.objects.get(id=int(user_id))
    page=int(page)
    if not(Group.objects.get(name="Administrator") in currentUser.groups.all() or user.id == currentUser.id):
        return HttpResponse("Sorry, you don't have permission to view %s's records"%user.username)
    start_date = datetime.strptime(start + " +0800", "%Y-%m-%d %z")
    end_date = datetime.strptime(end + " +0800", "%Y-%m-%d %z") + timedelta(0, 86399)
    records = Record.objects.filter(creater=user, UT_time__gte=start_date, UT_time__lte=end_date).order_by("-id")
    pageCount = ceil(len(records)/10.0)
    records = records[page*10:(page+1)*10]
    for record in records:
        record.UT_time = datetime.strftime(record.UT_time.astimezone(timezone(timedelta(0, 28800))), "%b. %d, %Y")
    return render(
        request,
        'UT/records.html',
        context_instance = RequestContext(request,
        {
            "records":records,
            "user_id":user_id,
            "start":start,
            "end":end,
            "range":range(1,pageCount+1),
            "currentpage":page+1,
        })
    )

def _add(article):
    path = article.split("/")
    if len(path)==3:
        relative_path = path[0]+"/"+path[1]+"/"
        filename = path[2]
    elif len(path)==2:
        relative_path = path[0]+"/"
        filename = path[1]
    else:
        return article+": relative path error", -1
    if filename[len(filename)-3:]==".md" or filename[len(filename)-3:]==".MD":
        filename = filename[:len(filename)-3]
    if relative_path == "articles/HDInsight/":
        relative_path = "articles/hdinsight/"
    articles = Article.objects.filter(filename=filename)
    try:
        service = Service.objects.get(relative_path=relative_path)
    except ObjectDoesNotExist:
        return article+": no service with this relative path", -1
    if len(articles)>0:
        for exist_article in articles:
            if exist_article.service.name != "Includes":
                return article+": is already in "+exist_article.service.name, -1
    new_article = Article(service=service, status="unknown", filename=filename)
    new_article.save()
    return article+": added", service.id

@never_cache
@login_required

reports/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
# Create your views here.

def mainpage(request):

    return HttpResponse("Currently under maintainance.")

UT/templates/UT/addArticles.html
{% extends "app/layout.html" %}

{% block content %}
<h2>Add Articles to the Database</h2>
<br />
<div style="border-bottom:dashed; border-width:1px; padding-bottom:5px">Please use the relative path of the articles in azure-content-mooncake-pr or azure-content-pr.</div>
<br />
<h4>Example:</h4>
<div>articles/app-service-web/web-sites-configure.md</div>
<br />
<div>
    <form method="post" action="">
        {% csrf_token %}
        <div>
            <textarea style="height:350px;width:100%" name="article_list"></textarea>
        </div>
        <div>
            <input type="submit" value="add"/>
        </div>
    </form>
    {% for log in logs %}
    <div>{{log}}</div>
    {% endfor %}
</div>
{% endblock %}

UT/templates/UT/articleList.html
{% for article in articles %}
<option value="{{article.id}}">{{article.filename}}</option>
{% endfor %}

UT/templates/UT/records.html
{% ifequal records|length 0 %}
Empty
{% else %}
{% for record in records %}
<h5>Record</h5>
<div>
    <span style="margin:10px 10px">Duration: {{record.duration}} minutes</span>
    <span style="margin:10px 10px">Labor Type: {{record.labor_type.type_name}}</span>
    <span style="margin:10px 10px">Owner: {{record.creater.username}}</span>
    <span style="margin:10px 10px">UT Date: {{record.UT_time}}</span>
</div>
<br />
<div>
    <span style="margin:10px 10px">Articles: 
        {% for record_article in record.record_article_set.all %}
            {{record_article.article.filename}},
        {% endfor %}
    </span>
</div>
<br />
<div style="border-bottom:dashed; border-width:1px; padding-bottom:5px">
    <span>Comments: {{record.comments}}</span>
</div>
<br />
{% endfor %}
<div>
    <span>page: </span>
    {% for page in range %}
    {% ifequal page currentpage %}
    <span>{{page}}</span>
    {% else %}
    <span><a href="javascript:getRecordsDuration({{user_id}}, '{{start}}', '{{end}}', {{page}}-1)">{{page}}</a></span>
    {% endifequal %}
    {% endfor %}
</div>
{% endifequal %}

UT/templates/UT/reportForAll.html
{% extends "app/layout.html" %}

{% block content %}
<script>
    function updateArticleList() {
        var xmlhttp;
        if (window.XMLHttpRequest)
        {
            xmlhttp=new XMLHttpRequest();
        }
        else
        {
            xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                document.getElementById("article_select_list").innerHTML = xmlhttp.responseText;
                document.getElementById("all_articles").innerHTML = xmlhttp.responseText;
                document.getElementById("cover").style.display = "none";
                document.getElementById("search_key").value = "";
            }
        }
        service = document.getElementById("service_select_list");
        xmlhttp.open("GET", "/ut/updatearticles/" + service.value + "/", true);
        xmlhttp.send();
        document.getElementById("cover").style.display = "block";
    }

    function addArticles() {
        article_select_list = document.getElementById("article_select_list");
        selected_article_list = document.getElementById("article_selected_list");
        for (i = 0; i < article_select_list.selectedOptions.length; i++) {
            isIn = false;
            for (j = 0; j < selected_article_list.options.length; j++) {
                if (selected_article_list.options[j].value == article_select_list.selectedOptions[i].value) {
                    isIn = true;
                    break;
                }
            }
            if (!isIn) {
                option = document.createElement("option");
                option.value = article_select_list.selectedOptions[i].value;
                option.innerHTML = article_select_list.selectedOptions[i].innerHTML;
                selected_article_list.appendChild(option);
            }
        }
    }
    function removeArticles() {
        selected_article_list = document.getElementById("article_selected_list");
        child_list = [];
        for (i = 0; i < selected_article_list.selectedOptions.length; i++) {
            child_list.push(selected_article_list.selectedOptions[i]);
        }
        for (i = 0; i < child_list.length; i++) {
            selected_article_list.removeChild(child_list[i]);
        }
    }
    function updateArticleIds() {
        selected_article_list = document.getElementById("article_selected_list");
        selected_article_ids = document.getElementById("article_ids");
        ids = "";
        for (i = 0; i < selected_article_list.options.length; i++) {
            ids += "" + selected_article_list.options[i].value + ",";
        }
        selected_article_ids.value = ids;
        document.getElementById("cover").style.display = "block";
    }

    function updateSelectedArticles(){
        selected_article_list = document.getElementById("article_selected_list");
        ul = document.getElementById("selected_articles");
        while (ul.firstChild) {
            ul.removeChild(ul.firstChild);
        }
        for (i = 0; i < selected_article_list.options.length; i++) {
            li = document.createElement("li");
            li.value = selected_article_list.options[i].value;
            li.innerHTML = selected_article_list.options[i].innerHTML;
            ul.appendChild(li);
        }
        document.getElementById("cover2").style.display = "none";
        document.getElementById("select_dia").style.display = "none";
    }
    function cancelSelectedArticles() {
        selected_article_list = document.getElementById("article_selected_list");
        while (selected_article_list.firstChild) {
            selected_article_list.removeChild(selected_article_list.firstChild)
        }
        ul = document.getElementById("selected_articles");
        lis = ul.getElementsByTagName("li");
        for (i = 0; i < lis.length; i++) {
            if (lis[i].value) {
                option = document.createElement("option");
                option.value = lis[i].value;
                option.innerHTML = lis[i].innerHTML;
                selected_article_list.appendChild(option);
            }
        }
        document.getElementById("cover2").style.display = "none";
        document.getElementById("select_dia").style.display = "none";
    }
    function editArticles() {
        document.getElementById("cover2").style.display = "block";
        document.getElementById("select_dia").style.display = "block";
    }
    function updateSearch() {
        search_key = document.getElementById("search_key").value.trim();
        article_select_list = document.getElementById("article_select_list");
        all_articles = document.getElementById("all_articles");
        while (article_select_list.firstChild) {
            article_select_list.removeChild(article_select_list.firstChild);
        }
        if (search_key == "") {
            for (i = 0; i < all_articles.options.length; i++) {
                article_select_list.appendChild(all_articles.options[i].cloneNode(true));
            }
        }
        else {
            for (i = 0; i < all_articles.options.length; i++) {
                if (all_articles.options[i].innerHTML.indexOf(search_key) > -1)
                    article_select_list.appendChild(all_articles.options[i].cloneNode(true));
            }
        }
    }
    function getRecordSearch(laborId) {
        var xmlhttp2;
        if (window.XMLHttpRequest) {
            xmlhttp2 = new XMLHttpRequest();
        }
        else {
            xmlhttp2 = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp2.onreadystatechange = function () {
            if (xmlhttp2.readyState == 4 && xmlhttp2.status == 200) {
                document.getElementById("searchResult").innerHTML = document.getElementById("searchResult").innerHTML+xmlhttp2.responseText;
                document.getElementById("cover").style.display = "none";
                document.getElementById("search_key").value = "";
            }
        }
        startDate = document.getElementById("startDate").value;
        endDate = document.getElementById("endDate").value;
        laborType = document.getElementById("laborType").value;
        xmlhttp2.open("GET", "/ut/recordsearch/" + laborId + "/from" + startDate + "to" + endDate + "/" + laborType + "/", true);
        xmlhttp2.send();
        document.getElementById("cover").style.display = "block";
    }
    function getRecords(user_id, record_num){
        var xmlhttp3;
        if (window.XMLHttpRequest) {
            xmlhttp3 = new XMLHttpRequest();
        }
        else {
            xmlhttp3 = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp3.onreadystatechange = function () {
            if (xmlhttp3.readyState == 4 && xmlhttp3.status == 200) {
                document.getElementById("recordDisplayContainer").innerHTML = xmlhttp3.responseText;
            }
        }
        xmlhttp3.open("GET", "/ut/getlogs/" + user_id + "/" + record_num + "/", true);
        xmlhttp3.send();
    }
    function getRecordsDuration(user_id, start, end, page){
        var xmlhttp5;
        if (window.XMLHttpRequest) {
            xmlhttp5 = new XMLHttpRequest();
        }
        else {
            xmlhttp5 = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp5.onreadystatechange = function () {
            if (xmlhttp5.readyState == 4 && xmlhttp5.status == 200) {
                document.getElementById("recordDisplayContainer").innerHTML = xmlhttp5.responseText;
            }
        }
        recordDisplayContainer = document.getElementById("recordDisplayContainer");
        recordDisplayContainer.innerHTML = "Loading...";
        xmlhttp5.open("GET", "/ut/getlogs/" + user_id + "/from" + start + "to" + end + "/" + page + "/", true);
        xmlhttp5.send();
    }
    function selectWithText(){
        document.getElementById("select_text").style.display = "block";
        document.getElementById("cover3").style.display = "block";
    }
    function cancelSelectWithText(){
        document.getElementById("select_text").style.display = "none";
        document.getElementById("cover3").style.display = "none";
        document.getElementById("select_article_text_area").value = "";
    }
    function updateSelectWithText(){
        var xmlhttp4;
        if (window.XMLHttpRequest) {
            xmlhttp4 = new XMLHttpRequest();
        }
        else {
            xmlhttp4 = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp4.onreadystatechange = function () {
            if (xmlhttp4.readyState == 4 && xmlhttp4.status == 200) {
                document.getElementById("article_selected_list").innerHTML = xmlhttp4.responseText;
                document.getElementById("cover").style.display = "none";
                cancelSelectWithText();
            }
        }
        xmlhttp4.open("POST", "/ut/selectarticleswithtext/", true);
        textArea = document.getElementById("select_article_text_area");
        text_list = textArea.value.replace(/\n/g, "%%n%%");
        xmlhttp4.setRequestHeader("text", text_list);
        xmlhttp4.send();
        document.getElementById("cover").style.display = "block";
    }
</script>
<style>
#cover {
   position: fixed;
   padding:0;
   margin:0;
   top:0;
   left:0;
   width: 100%;
   height: 100%;
   opacity: 0.80;
   background: #aaa;
   z-index: 14;
   display:none;
}
#cover2 {
   position:fixed;
   padding:0;
   margin:0;
   top:0;
   left:0;
   width: 100%;
   height: 100%;
   opacity: 0.80;
   background: #aaa;
   z-index: 10;
   display:none;
}

#cover3 {
   position:fixed;
   padding:0;
   margin:0;
   top:0;
   left:0;
   width: 100%;
   height: 100%;
   opacity: 0.80;
   background: #aaa;
   z-index: 12;
   display:none;
}

#select_dia {
   position: absolute;
   background: white;
   z-index: 11;
   width:960px;
   display:none;
}
#select_text {
   position: absolute;
   background: white;
   z-index: 13;
   width:400px;
   display:none;
}
</style>
<div id="cover">
    Getting article list...
</div>
<h2>{{ title }}</h2>
<h4>Labor Search For All</h4>
<div>
    <span>Start Date: <input type="date" id="startDate" value="{{start_day}}"/></span>
    <span>End Date: <input type="date" id="endDate" value="{{today}}"/></span>
    <span>Labor Type: 
        <select id="laborType">
            <option value="all">all</option>
            <option value="Deliverable">Deliverable</option>
            <option value="Undeliverable">Undeliverable</option>
        </select>
    </span>
    <span><input onclick="{% for user in users %}getRecordSearch({{user.id}});{% endfor %}" type="button" value="Search"/></span>
</div>
<div>
    <div>Labor Reporting: </div>
    <div id="searchResult">None</div>
</div>
<p></p>
{% endblock %}

UT/templates/UT/reportTable.html
<table border="1">
    <thead>
        <tr><td>Alias</td><td>Total Minutes</td><td>Total Hours</td><td>workdays</td><td>Percentage</td><td>Content Hours</td><td>Content Percentage</td></tr>
    </thead>
    <tr><td>{{username}}</td><td>{{totalminutes}}</td><td>{{totalhours}}</td><td>{{workdays}}</td><td>{{percentage}}</td><td>{{contenthours}}</td><td>{{contentpercentage}}</td></tr>
</table>

UT/templates/UT/selectArticles.html
{% for article in articles %}
<option value="{{article.id}}">{{article.filename}}</option>
{% endfor %}